### ISSUE TITLE
The Bouncy Castle 1.52 removes the PGPPublicKeyRingCollection(InputStream).

### ISSUE THREAD

**Issue by charleech** [verhas/License3j#13]
Dear Sir,

The Bouncy Castle 1.52 removes the  ```PGPPublicKeyRingCollection(InputStream) ```. 

By overview I've googled and found some example coding at [1]. If I'm not wrong it may be as the following: -

```java
//        final PGPPublicKeyRingCollection pgpRing = new PGPPublicKeyRingCollection(
//                PGPUtil.getDecoderStream(keyIn));
        final BcPGPPublicKeyRingCollection  pgpRing = new BcPGPPublicKeyRingCollection(
                                              PGPUtil.getDecoderStream(keyIn));
```
Could you please help to consider? Thank you very much for your help in advance. I'm looking forward to hearing from you soon.

Regards,

Charlee Ch.

[1] https://gerrit.googlesource.com/gerrit/+/2ec9cf967754f99a314646d9398fe888b54ea9a0

**Comment by rivella50** [comment]
I also would like it, if you could update your project to meet the latest Bouncy Castle version.
Is it planned ?

**Comment by verhas** [comment]
It is planned on best effort.

**Comment by verhas** [comment]
I pushed up a new version to the repository. Please play with it, check that you see it fits your needs and when you feedback positive I create a new release.

**Comment by rivella50** [comment]
Great to hear!
I will have a look at it tomorrow and let you know.
Thank you so far!

**Comment by rivella50** [comment]
Using the most recent Bouncy Castle libraries (version 1.52) i tested your latest code regarding encoding, decoding and using such a license file in a demo java app.
Everything worked fine!

**Comment by verhas** [comment]
Please check that 1.0.7 is available from central repo. If yes, I close this issue.

**Comment by rivella50** [comment]
It's available over sonatype, yes.
Could you please also update the following parts on the page home.html:
- new version 1.0.7 under Download and Installation (still 1.0.4)
- the URL is now http://central.sonatype.org/ and not http://www.sonatype.org/central anymore

Thank you!

**Comment by charleech** [comment]
I also have a change to test against the 1.0.7. It can decode the license correctly. I can confirm it.
