### ISSUE TITLE
signed key is not recognized by program

### ISSUE THREAD

**Issue by smarty1234** [verhas/License3j#15]
Exception in thread "main" java.lang.IllegalArgumentException: Can't find signing key in key ring.
        at com.verhas.licensor.License.loadKey(License.java:438)
        at com.verhas.licensor.License.loadKey(License.java:396)
        at com.verhas.licensor.License.loadKey(License.java:251)
        at License3j.encode(License3j.java:34)
        at License3j.main(License3j.java:150)
pub  4096R/ADADBA50  created: 2015-05-22  expires: never       usage: SC  
                     trust: ultimate      validity: ultimate
sub  4096R/BCEA7B3E  created: 2015-05-22  expires: never       usage: S   
[ultimate] (1). XXXXXXXX(Licensor at XXXX.com) <XXXXX@XXXXX.com>

**Comment by smarty1234** [comment]
can be closed.. documentation was not clear about creation of a signing authority first who would sign subsequent users of license.

**Comment by LH-Datarocks** [comment]
Hello,
could you please point out where in the documentation this part is described ?

**Comment by smarty1234** [comment]
https://github.com/verhas/License3j/blob/master/tuto.html

Download the whole stuff to your PC
I think sample.html and the tuto.html got the information that gives a fair idea what to do.

**Comment by LH-Datarocks** [comment]
Hi,
actually that's I did, but I came on the same error you opened the issue
about : Can't find signing key in key ring.
Maybe I didn't look right, but I found nothing related to signing authority
in the docs.

I'd be glad if you could point it out.

Thanks.

2015-06-25 17:13 GMT+04:00 smarty1234 <notifications@github.com>:

**Comment by smarty1234** [comment]
Yeah.. I am not before my PC now but I will respond today with more details.Try to create more than one user , the first one like Unix systems master user root and root created other users. Similar logic in creating certificate.
