### ISSUE TITLE
Passphrase asked when building with dependencies through NetBeans

### ISSUE THREAD

**Issue by smolinacadena** [verhas/License3j#17]
I am being asked a passphrase during building for the maven-gpg-plugin. Which passphrase is this?

**Comment by verhas** [comment]
That is the passphrase of the GPG key ring that contains the secret key. This is only needed when the package to be deployed into maven central is created. You do not do that.

If you modified the code for your needs and you want to deploy the modified version to your enterpise repo, then you have to comment out the `maven-gpg-plugin` configuration in `pom.xml` or configure it to skip. (Google: maven gpg sign skip)

**Comment by smolinacadena** [comment]
Thanks for the answer. I did the google search and was able to deploy License3j.
