### ISSUE TITLE
Command line tool not runnable (UNIX)

### ISSUE THREAD

**Issue by rnavarropiris** [verhas/License3j#19]
I tried to execute the `license3j.sh` script to encode a license, but it references a missing folder `lib`.

I built the project with maven

```
           mvn clean package
```

but neither are dependencies (bouncycastle) compiled together with the source code into a runnable jar file nor is this `lib` folder generated.

**Comment by verhas** [comment]
I was on a two week holiday. I will look at the issue.

**Comment by holle** [comment]
I grabbed bcpg-jdk15on-1.52.jarbcpkix-jdk15on-1.50.jar bcprov-jdk15on-1.52.jar (master brnach for 1.0.8-SNAPSHOT) from the maven repos/from the internet (maybe you need bcpg-jdk15on-1.50.jar bcpkix-jdk15on-1.50.jar bcprov-jdk15on-1.50.jar (older version, like i.e. 1.0.5)) and stored them into the "lib" folder.

Then I changed the Shellscript:

```bash
#! /bin/sh

cp="target/license3j-1.0.8-SNAPSHOT.jar"
for i in lib/*
do
cp=$cp:$i
done
java -cp $cp License3j $*
echo $cp
```

- Cheers, Holger

**Comment by fabiobsantos92** [comment]
I do what holle said but i still have this error using sh file
Error: Could not find or load main class License3j
If i execute the jar file directly, the dependencies jars like bouncycastle.

I still need help

**Comment by ericblue** [comment]
I just encountered this myself.  You need to make sure the lib directory not only contains the lincense3j jar file, but also the bouncycastle dependencies if they're not already on your classpath.  I found you needed the bcpg and bcprov jar files.  I just quickly symlinked them from my local maven repo, then re-ran the license3j.sh file with no issues.

E.g. my contents of lib
bcpg-jdk16-1.46.jar
bcprov-jdk16-1.46.jar
license3j-1.0.4.jar

**Comment by fertroya** [comment]
Why is this issue closed if the .sh file for the master branch still doesn't work? If running mvn assembly is required it could be provided as feedback when running the sh file. Running `mvn assembly:single` doesn't solve the issue either.
