### ISSUE TITLE
License3j package

### ISSUE THREAD

**Issue by IvanRF** [verhas/License3j#20]
Hi, thanks for sharing your great project!
I started following your tutorial to generate a license. When you mention the file `license3j.bat`, you said

> This time you have to start the command line processor included in the license3j JAR file.

But the JAR file in maven repository does not include that file, which I think is right. Maybe, you need to update the tutorial and link to this github project, since it is the only place where I found `license3j.bat`.

On the other hand, and here is the real issue, I included `license3j-1.0.7.jar` to my project in order to use `License3j.main(String[])`. However, this class is in the default package, thus **it is not possible to import it from a named package**. You can read about this [here](http://stackoverflow.com/questions/283816/how-to-access-java-classes-in-the-default-package).

I managed to call `License3j.main(String[])` using reflection, but I think that class should be inside `com.verhas` or `com.verhas.utils`.

**Comment by verhas** [comment]
This class is in the default package because that way it is easier to start the tool from the command line. On the other hand the `public static void main`, as usual, is not supposed to be invoked programmatically. There is the API to use the features of the package.

**Comment by IvanRF** [comment]
Hi Peter, thanks for your reply.
The are many libraries that include helpers like `License3j`, but they are **inside a package**.

Take [`WSDL2Java`](https://axis.apache.org/axis/java/apiDocs/org/apache/axis/wsdl/WSDL2Java.html) from Apache Axis as an example. You can see the reference [here](https://axis.apache.org/axis/java/reference.html):

> Usage: java org.apache.axis.wsdl.WSDL2Java [options] WSDL-URI

PS: Also, even that class call a main function from WSDL2Code: [code](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.axis2/axis2-codegen/1.4/org/apache/axis2/wsdl/WSDL2Java.java).

**Comment by verhas** [comment]
Since the latest version under development on branch jdk8 moves the class to a package from the default I close this issue.

**Comment by IvanRF** [comment]
Excellent, thanks!
