### ISSUE TITLE
CLI: Can't find signing key in key ring.

### ISSUE THREAD

**Issue by ma-hack** [verhas/License3j#22]
Hi Peter,

i have a problem to generate licenses on Linux (Ubuntu) machines. On Windows the license3j.bat works fine.

I get following exception: Exception in thread "main" java.lang.IllegalArgumentException: Can't find signing key in key ring.

The CLI call is:
./license3j.sh encode --license-file=liz.txt --keyring-file=secring.gpg --key="xxx (gfdsg) info@blabla.net" --password=gheim--output=liz.lic  

Have you an idea what the problem is? I tried Java SDK 6,7 and 8 wih the 1.0.8 release.

Best regards,
Marco

**Comment by holle** [comment]
I had the same problem and debugging showed that somehow the whitespace is a problem for the commandline args processor.
The --key="xxx (gfdsg) info@blabla.net" gets reduced to --key=xxx

Bummer :-(

call:
gpg --edit-key "xxx (gfdsg) info@blabla.net"
and run "adduid"
enter *just* a name w/o any blanks, no email, no comment.

Afterwards you can use the new uid to create licenses.

But beware! Both the checksum and the digest have changed.

- Cheers, Holger

**Comment by verhas** [comment]
Since this is more an operating system and shell usage problem, can I close the issue?
