### ISSUE TITLE
Keys are not generated as secring.pgp and pubring.pgp anymore

### ISSUE THREAD

**Issue by HJerem** [verhas/License3j#24]
**GnuPG** doesn't generate keys the same way as before... 
I tried to follow the tutorial but I can't since there are not `pubring.pgp` and `secring.pgp`.

Is there any way to make it work ?

**Comment by leoros71** [comment]
I am experiencing the same issue. Is there a way to make License3j work with GnuPG 2.1 ?

Thanks

**Comment by verhas** [comment]
It is not really a License3j issue, but I will look at it.

**Comment by leoros71** [comment]
Hi Peter,

Thanks for getting back to me.

I've sorted it out, generating .gpg files only requires two extra commands:

gpg --export > pubring.gpg

gpg --export-secret-keys > secring.gpg


Kind Regards,
Leopoldo

Il giorno ven 15 dic 2017 alle 08:23 Peter Verhas <notifications@github.com>
ha scritto:
