### ISSUE TITLE
LicenseDate class missing

### ISSUE THREAD

**Issue by pieterjvrensburg** [verhas/License3j#25]
Referring to the documentation on http://verhas.github.io/License3j/sample.html, the example shows using the LicenseDate class to verify the dates.

This is missing... Is there another way, or should I revert to standard date validation?

**Comment by verhasi** [comment]
Pieter hi,

"The class LicenseDate is a proprietary class of Groowiki that provides
date comparision for dates provided in the format YYYY-MM-DD which is
exclusively used for Groowiki licenses." It is the implementation of the
product that is using the License3j and could contain the business logic of
the product. It is different product by product so it can not be and is not
provided by the License3j intentionally.

bye
steve


2016-02-23 9:14 GMT+01:00 Pieter Janse van Rensburg <
notifications@github.com>:

**Comment by pieterjvrensburg** [comment]
Thank for you for explaining. Appreciate it.
