### ISSUE TITLE
problem to create license

### ISSUE THREAD

**Issue by andrescefe** [verhas/License3j#29]
I have this problem to create the license, "I was not found or loaded the main class com.javax0.license3j.License3j" when I run it from windows cmd.

**Comment by verhas** [comment]
Could you help me writing down which version you use? Also what prints this error message? The `License3j` class is in the default package in the current release and it is going to move the package `com.javax0.license3j` in the next release that is available in the branch`jdk8` currently and can be used.

**Comment by andrescefe** [comment]
The first error that I left was because I was taking the code from the file lincese.bat that is directly in the repository and I thought that was why, but download version 1.0.7 and when I am going to generate the license I get this error "Error no main class found or loaded License3j "I have jdk8.0_45

what am I doing wrong?

**Comment by klenkes74** [comment]
There has been a change. Formerly the main class has been "License3j", but now they changed it to "com.javax0.license3j.License3j".

So first you tried the new batch with the old java and now you are trying the old batch file with the new java. Just change the batchfile. Replace "License3j" by "com.javax0.license3j.License3j" and it should be fine.

**Comment by verhas** [comment]
Since there is no communication since the last feedback that, in my opinion, was a proper answer from klenkes74 I close this issue.

**Comment by prabhakarddriven** [comment]
'license3j' is not recognized as an internal or external command,
operable program or batch file i am getting this error please fix it

**Comment by prabhakarddriven** [comment]
when i am tring  to run this in CMD :- license3j decode --license-file=lic.txt --keyring-file=pubring.gpg
so i am gettion error

**Comment by verhas** [comment]
From the error message, I assume that the operating system is windows. In this case, the application has to be started from the directory where the installation was done. You can issue the `dir` command and see if there is a file `license3j.bat` in that directory. If this is not there then the installation was not correct. Please follow the documentation and then the installation will work fine.

The error seems to be a configuration and installation error and not a programming error, and as such, I cannot fix it.
