### ISSUE TITLE
Status of the 1.0.8 version

### ISSUE THREAD

**Issue by 3Dcube** [verhas/License3j#30]
What the status of the 1.0.8 version? Is it still under development? Should I use 1.0.7 version?
 Just inserted a few lines from the readme. 
```xml
        <dependency>
            <groupId>com.verhas</groupId>
            <artifactId>license3j</artifactId>
            <version>1.0.8</version>
        </dependency>
```
And I got:
```
Could not find artifact com.verhas:license3j:jar:1.0.8 in central (https://repo.maven.apache.org/maven2)
```

**Comment by verhas** [comment]
The latest release that was finalized, published and put into central maven repo is 1.0.7

The `readme.md` that you can read on the URL

https://github.com/verhas/License3j

is the latest snapshot release. The HEAD of the git repository, just as any other files in the git repository. This already is preparing for the next release, which is going to be 1.0.8

You can safely use the release 1.0.7 or you can download a snapshot version as depicted in

https://github.com/verhas/License3j/blob/master/pom.xml

compile it and go ahead using the new features that will be released in the new version.
