### ISSUE TITLE
Fraud Link Not Accessible

### ISSUE THREAD

**Issue by SZemanick** [verhas/License3j#34]
On the page [https://github.com/verhas/License3j/wiki/sample](https://github.com/verhas/License3j/wiki/sample) the fraud link is not accessible. 

_If you are debugging, not serious or for some other reason do not want this extra security check to be performed then you can pass null as second argument to method loadKeyRingFromResource(). For more information why you need to include your digest into the code and pass it to the key ring loading have a look at the page {{./fraud.html}}._

**Comment by verhas** [comment]
Thanks, fixed.
