### ISSUE TITLE
License lacking Dependencies and batch error

### ISSUE THREAD

**Issue by Fangueiro** [verhas/License3j#35]
Dear verhas,

The first issue I found is the lack of version 1.0.8 in the central repository. Which also seems not exist in the project.

The second, which I am having struggles with, is the error to find/load the main class. Either with package "com.javax0.license3j.License3j" or simply "License3j". I am using java 8 and the Windows .bat  file.

Moreover, I used the branch jdk8 and the license3j-1.0.7 tag with no success. Hope you can help, thank you.

**Comment by verhas** [comment]
1.0.8 was not released yet. That is the reason why you can not find it in the central repo. It is consistent with your finding that it is not in the project. When you look at the documentation and see that it talks about the version 1.0.8 you are looking at the documentation of the development version preparing for the next release.

The version in the branch `jdk8` has the main class in the package `com.javax0.license3j`. The windows BAT file defines this class on the line 161.
