### ISSUE TITLE
What's the LICENSE of this codebase?

### ISSUE THREAD

**Issue by geektown** [verhas/License3j#36]
hi @verhas ,
This is a great project.
Can this codebase be used in a commercial project? 
Can you add a LICENSE.txt file for this codebase, Apache License 2.0, MIT, or Others?
Thanks!

**Comment by verhas** [comment]
Thanks for warning me about the lack of the proper LICENSE.txt file. Of course, this project would be a kind of nonsense if I would not allow you to use in a commercial project.

It is said that it took several years until someone noticed that it is not properly licensed.

Have an Apache 2.0 `LICENSE.txt` in the root of the project.
