### ISSUE TITLE
maven jar 1.0.8 doesn't exist

### ISSUE THREAD

**Issue by CalyphoZz** [verhas/License3j#38]
Hello,

i am trying to bind a macAdress with a licence, but i can't use setUseHwAddress().
i was on licence3j 1.0.5 so i thought it was a versioning problem so i tried to put 1.0.8 but it dosen't exist?

my dependency : 
<dependency>
    <groupId>com.verhas</groupId>
    <artifactId>license3j</artifactId>
    <version>1.0.8</version>
</dependency>

i can't find any jar in 1.0.8, even after many time looking on the internet ?

tell me if i am doing wrong pls xD
Thanks,
Quentin.

**Comment by verhas** [comment]
The current version is 1.0.8-SNAPSHOT, which means that 1.0.8 was not released yet. That is why you can not find it.

**Comment by CalyphoZz** [comment]
To use the macAdress binding, i need 1.0.8 version?

**Comment by verhas** [comment]
I assume that you intended to write a question and not a statement. If it is a statement, then it is not true.

The last official release 1.0.5 also supports macAddress binding.

**Comment by CalyphoZz** [comment]
Ok thanks for your answser...do i have to bind the mac adress when i create the licence ? or at an other moment? sorry to be annoying but i don't find how to use explicitly HardwareBinder.

**Comment by verhas** [comment]
The hardware binder is just a helping API that you can use in your license checking code. You can get the information about the hardware IDs of the machine and encode it into the license as an attribute and then do the checking along with the license checking.
