### ISSUE TITLE
Please release to central with Java 8

### ISSUE THREAD

**Issue by shevek** [verhas/License3j#43]
The central release was compiled with Java 10 and uses class file version 54.

Please can you compile with java 7 or 8 so it can be used more widely?

**Comment by verhas** [comment]
```
<dependency>
    <groupId>com.verhas</groupId>
    <artifactId>license3j</artifactId>
    <version>2.0.0-JVM8</version>
    <packaging>jar</packaging>
</dependency>
```

should work as soon as the processes run through the central repo.
