### ISSUE TITLE
Bytes output from digest command do not include algorithm

### ISSUE THREAD

**Issue by cwash** [verhas/License3j#47]
https://github.com/verhas/License3j/blob/872adc9993ea8a32a56cb48230b070de31baa1ca/src/main/java/javax0/license3j/CommandLineApp.java#L187

Shouldn't this line use `keyPair.getPublic()` - which seems to include the algorithm - and not just the encoded byte portion - when generating the byte array of the public key to place in your application?

When testing this, I couldn't get it to work with just the encoded byte portion.  Upon attempting to load the public key in, the LicenseKeyPair.getAlgorithm() call would always fail in this code block, because it was not finding the right ASCII byte representation of the algorithm at the beginning of `buffer`.

`
        private static String getAlgorithm(byte[] buffer){
            for(int i = 0 ; i < buffer.length ; i ++){
                if( buffer[i] == 0x00){
                    return new String(Arrays.copyOf(buffer,i),StandardCharsets.UTF_8);
                }
            }
            throw new IllegalArgumentException("key does not contain algorithm specification");
        }
`

After changing `keyPair.getPair().getPublic().getEncoded()` to just `keyPair.getPublic()` things seemed to work better for me.

**Comment by verhas** [comment]
Pull request accepted, merged.
