### ISSUE TITLE
UTC in unit tests

### ISSUE THREAD

**Issue by giorgioinf** [verhas/License3j#51]
In the travis, the unit tests are working properly, I guess it may be running in UTC timezone.

In my case, and probably most of other people laptops, the timezone ins't UTC, and the tests should be work correctly in different timezones.

Basically we can fix it changing:   
```java
final var now = new Date(1545047719295L);
```
to
```java
final var now = Date.from(LocalDateTime.of(2018,12, 17, 12, 55, 19, 295 * 1000000)
                .toInstant(ZoneOffset.UTC));
```

**Comment by verhas** [comment]
This is nonsense.

A Date is a certain point in time independent of the time zone. You can be in London, Vladivostok or on the moon.

When you create a Date object as in `new Date(1545047719295L)` then you specify the time that is `1545047719295` seconds later than the universal time point when in was January 1, 1970, 00:00:00 in Greenwich. (Btw: documentation of Date talks about GMT and not UTC.)

This `long` number is stored in a license Date feature. When you pass a `Date` object the long number is retrieved using `getTime()`, and when it is returned as a Date object the `new Date()` is used in the implementation.

This has nothing to do with time zones. There is one time zone: GMT.

My development machine is not in GMT and all tests work fine. If the test fails on your machine it certainly has to be some other problem.
