### ISSUE TITLE
Documentation for Java8?

### ISSUE THREAD

**Issue by vinaykr91** [verhas/License3j#56]
Hi , I am using `"license3j-2.0.0-JVM8.jar"` with Java 8 . The commands given in the documentation refer to Java 11 commands.  There is no Repl class in this jar. 

So can you please share the commands to create the license file with this jar. 
Thank you.

**Comment by verhas** [comment]
You can read the documentation of that version in the branch 

https://github.com/verhas/License3j/tree/release-2.0.0-JVM8

That is an old version of License3j. Repl is supported starting with version 3.0.0 as an experimental tool and it will be supported only as a full-fledged GA available tool in release 3.1.0

I do not plan to release Java 8 version of License3j 3.0.0 versions.

I recommend that you upgrade your Java code to Java 11 or even to Java 12 now.

Regards,
Peter

**Comment by vinaykr91** [comment]
This is really helpful. Everything is working fine for me.

I will bring up your suggestions during our next team meeting.

Thank you.
