### ISSUE TITLE
Date serialization is TZ-dependent

### ISSUE THREAD

**Issue by shevek** [verhas/License3j#58]
Needs to use an Instant type and an ISO format. You're clearly living and testing in UTC+1 or UTC-1, because all your test cases are an hour out. I have a test cluster across multiple timezones.

**Comment by verhas** [comment]
Thank you very much for the bug report.

Date serialization is not TZ dependent though. It is the only conversion to and from text representation that was time zone dependent.

Please use the now available release 3.1.1 where this bug is fixed.
