### ISSUE TITLE
Using License3J on Java 8 for linux

### ISSUE THREAD

**Issue by ElemenT5ven** [verhas/License3j#59]
Hello, I can only use java 8, but I still want to use your License3j.
Should I try the 2.0.0 release ? Or it is already outdated?

**Comment by verhas** [comment]
It is not outdated in the sense that it can be used. Just be prepared that the license handling and license format is totally different in later versions. Whenever you migrate to Java 11 and the new version of License3j you will have to replace all the issued license files and rewrite the license handling API. You can also use the old version of License3j and Java 9 or later. This is also a possibility. It is up to you.

The fact that there is a newer version does not make the old version any worse. It is just as good as it was before.

**Comment by verhas** [comment]
Btw. License3j 2.0.0 also requires Java 10 as a minimum.

**Comment by ElemenT5ven** [comment]
Ok, I should be on the License3j 1.0.8 version.
Is there a major difference between 1.0.8 and 2.0.0 version?

**Comment by ElemenT5ven** [comment]
I tried the 2.0.0, it didn't tell me any problems

**Comment by ElemenT5ven** [comment]
I want to run it on linux, the license3j.bat file is for window right? So is here any other way?

**Comment by verhas** [comment]
You can try to use `license3j.sh`. That may work under Linux.

**Comment by ElemenT5ven** [comment]
license3j.bat encode --license-file=license-plain.
txt --keyring-file="c:\Documents and Settings\verhas\Application Data\gnupg\secr
ing.gpg" --key=GrooWikiDemoKey --password=******** --output=license.out

this is the command you ask us to do for generate the license file with window, I don't think license3j.sh do the same as license3j.bat do for linux

**Comment by ElemenT5ven** [comment]
Or maybe shoud I use windows to generate license file and linux for the validation of the license file?

**Comment by ElemenT5ven** [comment]
"This time you have to start the command line processor included in the license3j JAR file."
When you said this just before telling us to do the license3j.bat encode:
- what is the command line processor?
- And where can we find the license3j JAR file? (tried mvn package but didn t work)

**Comment by ElemenT5ven** [comment]
You were right, it seem, I can't use java 8 for License3j 2.0.0 to generate license.
May I ask you to upload the version 1.0.8 of License3j?

**Comment by ElemenT5ven** [comment]
java -cp target/license3j-2.0.0-JVM8.jar com.javax0.license3j.License3j encode --license-file=license-plain.txt --keyring-file=secring.gpg --key=licensetest --password=password --output=license.out

I get this after the command above, what is the meaning of this error? I have org.bouncycastle version 1.57 in your pom.xml as dependency from your 2.0.0 release git

Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/openpgp/PGPException
	at com.javax0.license3j.License3j.encode(License3j.java:97)
	at com.javax0.license3j.License3j.main(License3j.java:86)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.openpgp.PGPException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by verhas** [comment]
You can download all the published versions from 

https://mvnrepository.com/artifact/com.verhas/license3j

**Comment by verhas** [comment]
The License3j version 2.0.0 has a dependency on the BouncyCastle library, as you can see in the POM file. This library needs to be there on the classpath when the application runs and not only during compile time.

Your command line has only the license3j JAR file on the classpath.

**Comment by ElemenT5ven** [comment]
I tried this one alse, but still I get the same error:

java -cp target/license3j-2.0.0-JVM8.jar:/home/ivan/.m2/repository/org/bouncycastle/bcpg-jdk15on/1.57/bcpg-jdk15on-1.57-sources.jar:/home/ivan/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.57/bcprov-jdk15on-1.57-sources.jar:/home/ivan/.m2/repository/org/mockito/mockito-all/1.10.17/mockito-all-1.10.17-sources.jar:/home/ivan/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.2.0/junit-jupiter-api-5.2.0-sources.jar:/home/ivan/.m2/repository/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0-sources.jar:/home/ivan/.m2/repository/org/opentest4j/opentest4j/1.1.0/opentest4j-1.1.0-sources.jar:/home/ivan/.m2/repository/org/junit/platform/junit-platform-commons/1.2.0/junit-platform-commons-1.2.0-sources.jar:/home/ivan/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.2.0/junit-jupiter-engine-5.2.0-sources.jar:/home/ivan/.m2/repository/org/junit/platform/junit-platform-engine/1.2.0/junit-platform-engine-1.2.0-sources.jar com.javax0.license3j.License3j encode --license-file=license-plain.txt --keyring-file=secring.gpg --key=licensetest --password=password --output=license.out



Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
	at com.javax0.license3j.License3j.encode(License3j.java:97)
	at com.javax0.license3j.License3j.main(License3j.java:86)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)

**Comment by verhas** [comment]
There is no surprise. You will get the same error again and again while you do not have the BouncyCastle library on the classpath. You have a lot of unused libraries on the classpath, but the BouncyCastle library is not on the classpath.
