### ISSUE TITLE
The Bouncy Castle 1.51 removes the PGPSecretKey.extractPrivateKey(String)

### ISSUE THREAD

**Issue by charleech** [verhas/License3j#6]
Dear Sir,

The Bouncy Castle 1.51 removes the ``` PGPSecretKey.extractPrivateKey(String)  ```, it cause the License3j some exception as

java.lang.NoSuchMethodError: org.bouncycastle.openpgp.PGPSecretKey.extractPrivateKey([CLjava/lang/String;)Lorg/bouncycastle/openpgp/PGPPrivateKey;
	at com.verhas.licensor.License.encodeLicense(License.java:482)

By overview I've googled and found some example coding at [1]. If I'm not wrong it may be as the following: -
```java
        PGPSecretKey                key          = null;
        String                      pin          = null;
        PGPDigestCalculatorProvider calcProvider = null;
        PBESecretKeyDecryptor       decryptor    = null;
        PGPPrivateKey               pKey         = null;
        try {
            key          = //Loading key
            pin          = "some-pin";
            calcProvider = new JcaPGPDigestCalculatorProviderBuilder().
                                    setProvider(BouncyCastleProvider.PROVIDER_NAME).
                                    build();
            decryptor    = new JcePBESecretKeyDecryptorBuilder(calcProvider).
                                    setProvider(BouncyCastleProvider.PROVIDER_NAME).
                                    build(pin.toCharArray());
            pKey         = key.extractPrivateKey(decryptor);
            
        } catch (PGPException e) {
            // TODO Handle the exception
            e.printStackTrace();
        } finally {
            key          = null;
            pin          = null;
            calcProvider = null;
            decryptor    = null;
            pKey         = null;
        }
```

Could you please help to consider? Thank you very much for your help in advance. I'm looking forward to hearing from you soon.

Regards,

Charlee Ch.

[1] https://github.com/bcgit/bc-java/blob/master/pg/src/test/java/org/bouncycastle/openpgp/test/PGPUnicodeTest.java

**Comment by verhas** [comment]
Since this is an olc issue and the current version is using BC 1.52 I close this issue.
