### ISSUE TITLE
License verification on Ubuntu vs Windows

### ISSUE THREAD

**Issue by kedarpanse** [verhas/License3j#61]
I am having a weird issue where license verification. For me same license and same public key works in Windows but it does not work on Ubuntu 

![Windows](https://user-images.githubusercontent.com/40928481/69140866-6d8f7f80-0ae9-11ea-81cc-1c07b4ded18f.png)

This works as expected but when I try same exact files on Ubuntu machine:

![Ubuntu](https://user-images.githubusercontent.com/40928481/69140876-71bb9d00-0ae9-11ea-90ef-77ef166934a0.png)

What could cause this issue?

**Comment by verhas** [comment]
My first guess is that the keys are not the same on the two systems.

**Comment by kedarpanse** [comment]
No I have copied same exact files, it is same in fact I have generated only one key

**Comment by artem-mozgovoy** [comment]
have opposite situation with my teammate. 
Signed file properly validating on Ubuntu, but fails on digest check step on windows.

@kedarpanse do you have any luck with your case?

**Comment by kedarpanse** [comment]
@artem-mozgovoy no I have not spent enough time on it yet. I will need to debug this, but I suspect something to do with the binary stringer/unstringer using default Base64 encoding of java.  
It seems, some people have found that it differs on unix/windows as no charset is specified and defaults may vary based on jvm. Ideally it should be ISO_8859_1

https://stackoverflow.com/questions/12323581/base64encoder-results-differ-from-windows-to-unix

**Comment by verhas** [comment]
The cited stackoverflow article concludes that the call to `getBytes()` without argument is OS specific. License3j uses `getBytes(StandardCharsets.UTF_8)` everywhere, thus this cannot be the problem.

**Comment by marioc-bitheads** [comment]
I'm all having a similar issue between macOS and Android. @kedarpanse did you figure out the issue?

**Comment by verhas** [comment]
Could you give it a try with the version 3.1.4 ? There is a bug fix that corrects reading license files from disk.

**Comment by kedarpanse** [comment]
I just tried it, that was it.  It seems to be working now.  One thing I noticed though, old license will not work with newer version. I  had a license created with 3.1.0 they didnt work. I had to recreate using 3.1.4. 

Thanks a lot! May I ask what caused it?

**Comment by verhas** [comment]
When you specify a cipher then the first part till the `/` character is the algorithm and this is used to get the algorithm. However, when the cipher is saved into the binary file and is read back the part after the `/` and the `/` is not chopped off before trying to use it as an algorithm identifier. Some Java implementations seem to be resilient to this and use the algorithm that is at the start of the cipher, others, like the one you experienced not.

What bothers me, however, that this fix should make it able to work with a license that was created with a prior version. This is a change only how we read back the algorithm from the license file.

The binary format of the license is documented in detail in the documentation, I even created detailed diagrams about it. If you still have the old licenses it would be interesting to see why it is not loaded.

**Comment by marioc-bitheads** [comment]
I tried 3.1.4 and I am still not able to validate. 

Here's in more detail my situation: 

- Generate a license (Base64 encoded file) on macOS (OpenJDK 11 built) 
- Read and validate license works fine on Docker container (i.e. Linux inside Docker, works on macOS and Linux hosts)
- From Android downloads the license file to memory and pass it to LicenseReader as a ByteArrayInputStream. 

I can read the license data just fine, but validation fails.

**Comment by marioc-bitheads** [comment]
I figured out what is the issue on Android v 8 (Oreo).
the Cipher need to be more explicit, I was able to get this code to properly validate 

`
final MessageDigest digester = MessageDigest.getInstance("SHA-512");
final byte[] ser = license.unsigned();
final byte[] digestValue = digester.digest(ser);
final PublicKey pKey = LicenseKeyPair.Create.from(publicKey, Modifier.PUBLIC).getPair().getPublic();
final Cipher cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");
cipher.init(Cipher.DECRYPT_MODE, pKey);
final byte[] sigDigest = cipher.doFinal(license.getSignature());
if (Arrays.equals(digestValue, sigDigest)) {
    System.out.println(" ***********   SUCCESSS ***********");
} else {
    System.out.println(" -----------   FAILED -----------");
}
`

This is not ideal as it hardcode the Cipher, but for now I can live with that.

**Comment by kedarpanse** [comment]
> 
> 
> When you specify a cipher then the first part till the `/` character is the algorithm and this is used to get the algorithm. However, when the cipher is saved into the binary file and is read back the part after the `/` and the `/` is not chopped off before trying to use it as an algorithm identifier. Some Java implementations seem to be resilient to this and use the algorithm that is at the start of the cipher, others, like the one you experienced not.
> 
> What bothers me, however, that this fix should make it able to work with a license that was created with a prior version. This is a change only how we read back the algorithm from the license file.
> 
> The binary format of the license is documented in detail in the documentation, I even created detailed diagrams about it. If you still have the old licenses it would be interesting to see why it is not loaded.
I do have one attached:


[ValidLicense.txt](https://github.com/verhas/License3j/files/4173917/ValidLicense.txt)

**Comment by verhas** [comment]
I close this issue. If there is still something outstanding, you can reopen it.
