### ISSUE TITLE
License file is not closed after reading it

### ISSUE THREAD

**Issue by jayudhandha** [verhas/License3j#62]
Hi,

I am using license3j to read the license file that i have.

It seems, It's not closing the inputstream whenever we are reading the license file.

I am using `setLicenseEncodedFromFile(File, CharSet)` method.

Below is the piece of code that i seen in `License` class

```
public License setLicenseEncoded(InputStream inputStream, String charset)
        throws IOException, PGPException {
        final ByteArrayInputStream keyIn = new ByteArrayInputStream(
            publicKeyRing);
        final InputStream decoderInputStream = PGPUtil
            .getDecoderStream(inputStream);
}    
```

Here inside `getDecoderStream` we are only reseting the inputStream, We are not closing after reading it.

Am i doing something wrong?

Please help!

**Comment by verhas** [comment]
This seems to be a bug in that old version.

Please consider using the newest version of License3j.
