### ISSUE TITLE
Improve performance by reducing / deferring Stream terminal operations

### ISSUE THREAD

**Issue by dkcm** [verhas/License3j#68]
Thanks @verhas, great library.  I plan to leverage your library in a project so took a deep dive into the code.

Suggest the following to improve performance:
1. Prefer `NetworkInterface.networkInterfaces()`, which returns a `Stream`  https://github.com/verhas/License3j/blob/2be3a2654adc721c2747307c1ab6fe74488a3def/src/main/java/javax0/license3j/hardware/Network.java#L28

1. Return a `Stream` instead of collecting into a `List` https://github.com/verhas/License3j/blob/2be3a2654adc721c2747307c1ab6fe74488a3def/src/main/java/javax0/license3j/hardware/Network.java#L30

1. So here we can call `sorted` (an intermediate operation) instead of `sort` https://github.com/verhas/License3j/blob/2be3a2654adc721c2747307c1ab6fe74488a3def/src/main/java/javax0/license3j/hardware/HashCalculator.java#L37

1. Finally, terminal operation here on the `Stream` `interfaces.forEach(ni -> ...` https://github.com/verhas/License3j/blob/2be3a2654adc721c2747307c1ab6fe74488a3def/src/main/java/javax0/license3j/hardware/HashCalculator.java#L27

I would be happy to raise a PR for the above this weekend, if you like.

**Comment by verhas** [comment]
>I would be happy to raise a PR for the above this weekend, if you like.

Yes, please... I very much welcome your cleanup, They absolutely make sense.
