### ISSUE TITLE
Wishlist: 

### ISSUE THREAD

**Issue by 4braincells** [verhas/License3j#87]
As enums cannot be extended, I'd like to implement an own CloudProvider enum class.
Could you (or me in consent with you guys) refactor the CloudProvide so that I can write my own CloudProvider Enum?
Thx

**Comment by verhas** [comment]
I have added a proprietary cloud provider, for which there are two setters. Using these, you can set the URL and the headers, and following that, you can query the identity.

Feel free to create any pull request with suggestions if you feel this does not solve the issue or if you feel this is not a good solution.
