### ISSUE TITLE
Tests fail with JVM 13 and 17 

### ISSUE THREAD

**Issue by 4braincells** [verhas/License3j#88]
[INFO] 
[INFO] -------------------< com.javax0.license3j:license3j >-------------------
[INFO] Building License3j 3.2.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ license3j ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/ssc/Documents/30 Projects/License3j/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ license3j ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ license3j ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ license3j ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ license3j ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running javax0.license3j.crypto.LicenseSignerTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.942 s - in javax0.license3j.crypto.LicenseSignerTest
[INFO] Running javax0.license3j.parsers.NumericParserTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 s - in javax0.license3j.parsers.NumericParserTest
[INFO] Running javax0.license3j.hardware.TestInterfaceSelector
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.13 s - in javax0.license3j.hardware.TestInterfaceSelector
[INFO] Running javax0.license3j.TestFeatureSerialization
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 s - in javax0.license3j.TestFeatureSerialization
[INFO] Running javax0.license3j.io.TestKeyPairReader
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.014 s <<< FAILURE! - in javax0.license3j.io.TestKeyPairReader
[ERROR] javax0.license3j.io.TestKeyPairReader.canReadPrivateKeyFromBinaryFile  Time elapsed: 0.003 s  <<< ERROR!
java.io.FileNotFoundException: /Users/ssc/Documents/30%20Projects/License3j/target/test-classes/javax0/license3j/io/private.key.binary (No such file or directory)
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestKeyPairReader.canReadPrivateKeyFromBinaryFile(TestKeyPairReader.java:25)
[ERROR] javax0.license3j.io.TestKeyPairReader.canReadPublicKeyFromBinaryFile  Time elapsed: 0 s  <<< ERROR!
java.io.FileNotFoundException: /Users/ssc/Documents/30%20Projects/License3j/target/test-classes/javax0/license3j/io/public.key.binary (No such file or directory)
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestKeyPairReader.canReadPublicKeyFromBinaryFile(TestKeyPairReader.java:16)
[ERROR] javax0.license3j.io.TestKeyPairReader.canReadPrivateKeyFromBase64File  Time elapsed: 0.001 s  <<< ERROR!
java.io.FileNotFoundException: /Users/ssc/Documents/30%20Projects/License3j/target/test-classes/javax0/license3j/io/private.key.base64 (No such file or directory)
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestKeyPairReader.canReadPrivateKeyFromBase64File(TestKeyPairReader.java:43)
[ERROR] javax0.license3j.io.TestKeyPairReader.throwsUpOnStringFormat  Time elapsed: 0.001 s  <<< ERROR!
java.io.FileNotFoundException: /Users/ssc/Documents/30%20Projects/License3j/target/test-classes/javax0/license3j/io/private.key.base64 (No such file or directory)
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestKeyPairReader.throwsUpOnStringFormat(TestKeyPairReader.java:52)
[ERROR] javax0.license3j.io.TestKeyPairReader.canReadPublicKeyFromBase64File  Time elapsed: 0 s  <<< ERROR!
java.io.FileNotFoundException: /Users/ssc/Documents/30%20Projects/License3j/target/test-classes/javax0/license3j/io/public.key.base64 (No such file or directory)
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestKeyPairReader.canReadPublicKeyFromBase64File(TestKeyPairReader.java:34)
[INFO] Running javax0.license3j.io.TestLicenseWriter
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 s - in javax0.license3j.io.TestLicenseWriter
[INFO] Running javax0.license3j.io.TestLicenseReader
[ERROR] Tests run: 5, Failures: 1, Errors: 4, Skipped: 0, Time elapsed: 0.013 s <<< FAILURE! - in javax0.license3j.io.TestLicenseReader
[ERROR] javax0.license3j.io.TestLicenseReader.canReadLicenseFromBase64File  Time elapsed: 0.003 s  <<< ERROR!
java.io.FileNotFoundException: /Users/ssc/Documents/30%20Projects/License3j/target/test-classes/javax0/license3j/io/temporaryLicenseFile.base64 (No such file or directory)
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestLicenseReader.canReadLicenseFromBase64File(TestLicenseReader.java:41)
[ERROR] javax0.license3j.io.TestLicenseReader.avoidTooLongFile  Time elapsed: 0.002 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <java.lang.IllegalArgumentException> but was: <java.io.FileNotFoundException>
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestLicenseReader.avoidTooLongFile(TestLicenseReader.java:50)
Caused by: java.io.FileNotFoundException: /Users/ssc/Documents/30%20Projects/License3j/target/test-classes/javax0/license3j/io/temporaryLicenseFile.txt (No such file or directory)
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestLicenseReader.lambda$avoidTooLongFile$0(TestLicenseReader.java:51)
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestLicenseReader.avoidTooLongFile(TestLicenseReader.java:50)
[ERROR] javax0.license3j.io.TestLicenseReader.canReadLicenseFromBinaryFile  Time elapsed: 0.001 s  <<< ERROR!
java.io.FileNotFoundException: /Users/ssc/Documents/30%20Projects/License3j/target/test-classes/javax0/license3j/io/temporaryLicenseFile.binary (No such file or directory)
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestLicenseReader.canReadLicenseFromBinaryFile(TestLicenseReader.java:23)
[ERROR] javax0.license3j.io.TestLicenseReader.canReadDefaultLicenseFromBinaryFile  Time elapsed: 0.001 s  <<< ERROR!
java.io.FileNotFoundException: /Users/ssc/Documents/30%20Projects/License3j/target/test-classes/javax0/license3j/io/temporaryLicenseFile.binary (No such file or directory)
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestLicenseReader.canReadDefaultLicenseFromBinaryFile(TestLicenseReader.java:32)
[ERROR] javax0.license3j.io.TestLicenseReader.canReadLicenseFromTextFile  Time elapsed: 0.001 s  <<< ERROR!
java.io.FileNotFoundException: /Users/ssc/Documents/30%20Projects/License3j/target/test-classes/javax0/license3j/io/temporaryLicenseFile.txt (No such file or directory)
	at com.javax0.license3j@3.2.0/javax0.license3j.io.TestLicenseReader.canReadLicenseFromTextFile(TestLicenseReader.java:14)
[INFO] Running javax0.license3j.io.TestKeyPairWriter
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.139 s - in javax0.license3j.io.TestKeyPairWriter
[INFO] Running javax0.license3j.TestHardwareBinder
The UUID of the machine is:
0c817b52-5cb2-3a26-9eb6-f8d7c45096eb
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.115 s - in javax0.license3j.TestHardwareBinder
[INFO] Running javax0.license3j.LicenseTest
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.558 s - in javax0.license3j.LicenseTest
[INFO] Running javax0.license3j.TestFeature
[INFO] Tests run: 50, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.068 s - in javax0.license3j.TestFeature
[INFO] Running javax0.license3j.TestRevocableLicense
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 s - in javax0.license3j.TestRevocableLicense
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestLicenseReader.avoidTooLongFile:50 Unexpected exception type thrown ==> expected: <java.lang.IllegalArgumentException> but was: <java.io.FileNotFoundException>
[ERROR] Errors: 
[ERROR]   TestKeyPairReader.canReadPrivateKeyFromBase64File:43 » FileNotFound /Users/ssc...
[ERROR]   TestKeyPairReader.canReadPrivateKeyFromBinaryFile:25 » FileNotFound /Users/ssc...
[ERROR]   TestKeyPairReader.canReadPublicKeyFromBase64File:34 » FileNotFound /Users/ssc/...
[ERROR]   TestKeyPairReader.canReadPublicKeyFromBinaryFile:16 » FileNotFound /Users/ssc/...
[ERROR]   TestKeyPairReader.throwsUpOnStringFormat:52 » FileNotFound /Users/ssc/Document...
[ERROR]   TestLicenseReader.canReadDefaultLicenseFromBinaryFile:32 » FileNotFound /Users...
[ERROR]   TestLicenseReader.canReadLicenseFromBase64File:41 » FileNotFound /Users/ssc/Do...
[ERROR]   TestLicenseReader.canReadLicenseFromBinaryFile:23 » FileNotFound /Users/ssc/Do...
[ERROR]   TestLicenseReader.canReadLicenseFromTextFile:14 » FileNotFound /Users/ssc/Docu...
[INFO] 
[ERROR] Tests run: 118, Failures: 1, Errors: 9, Skipped: 0
[INFO]

**Comment by verhas** [comment]
![image](https://user-images.githubusercontent.com/1597979/158335850-403cedf8-a381-44a7-bab1-6e98c1909310.png)

To solve this issue the depednency to mockito has to be updated to the newest release.
