### ISSUE TITLE
Exception while serializing Feature to JSON, e.g. DATE Feature not regocnized as DATE.

### ISSUE THREAD

**Issue by 4braincells** [verhas/License3j#90]
I created a License with a couple of features.
When I convert them to JSON by

            var objectMapper = new ObjectMapper();
            String requestBody = objectMapper
                    .writeValueAsString(licenseViolation);

I get the exception "Feature is not BIGDECIMAL" and don't see which feature is meant.
I dont have any feature defined as BIGDECIMAL.

One Feature is a STRING containing a number "1".
Can this be the cause?
I also dont find any clue in the code ...

Thx

**Comment by 4braincells** [comment]
![Bildschirmfoto 2022-07-06 um 09 12 37](https://user-images.githubusercontent.com/34167411/177492020-b712766f-5f95-4b9b-af33-44b63479a2c4.png)
![Bildschirmfoto 2022-07-06 um 09 11 58](https://user-images.githubusercontent.com/34167411/177492025-8bd505b7-4aeb-4341-9919-b643afdb9f10.png)
![Bildschirmfoto 2022-07-06 um 09 12 08](https://user-images.githubusercontent.com/34167411/177492027-a6afe74b-c7dc-4eb7-82da-e05719c316f9.png)

Now still struggling with the question how Feature , when called for serialisation in Jackson,
comes to the decision to check a DATE feature as BIGDECIMAL, BINARY or INT (seems to be a RANDOM decision)

**Comment by 4braincells** [comment]
OK, found. "Feature" is not serializable *) by Jackson. Which makes it a bit nasty to dump the license/features to a JSON string.

*) because throwing exeptions in getters (which aren't getters anyway) is a very "creative" approach ...

**Comment by verhas** [comment]
Jackson serialization tries to use the fields as well as the getters of the object. In these cases, Jackson thinks that the methods starting `get` are getters. They are kind of getters, but not strict Java beans getters. The solution is to tell Jackson not to try to be smarter than it is and to configure the mapper not to use the getters, only the fields.

On this 

https://stackoverflow.com/questions/7105745/how-to-specify-jackson-to-only-use-fields-preferably-globally

StackOverflow page you can get a detailed description of how that can be done. I personally have not verified that, but this would be the way where I would start to go.

>>because throwing exceptions in getters (which aren't getters anyway) is a very "creative" approach ...

I understand your frustration and I am sorry about that. It seemed to be a good idea. Many users use this little library, and thus it is not feasible to change it.
